### ISSUE TITLE
Unable to add a batch

### ISSUE THREAD

**Issue by anandology** [fossunited/community#123]
**Describe the bug**
"Add new batch/ Create your first batch" link is failing with a traceback.

**To Reproduce**
1. Go to Course page as a mentor
2. Click on add new batch

**Expected behavior**
Form should be displayed to add a new batch.

**Traceback**

```
Traceback (most recent call last):
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/modules/utils.py", line 205, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/__init__.py", line 938, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'community.community.doctype.community_course_member.community_course_member'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/app.py", line 77, in application
    response = frappe.website.render.render()
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/website/render.py", line 46, in render
    data = render_web_form(path)
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/website/render.py", line 111, in render_web_form
    data = render_page(path)
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/website/render.py", line 194, in render_page
    return build(path)
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/website/render.py", line 201, in build
    return build_page(path)
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/website/render.py", line 216, in build_page
    context = get_context(path)
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/website/router.py", line 40, in get_page_context
    page_context = make_page_context(path)
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/website/router.py", line 48, in make_page_context
    context = resolve_route(path)
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/website/router.py", line 26, in resolve_route
    return get_page_context_from_doctype(path)
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/website/router.py", line 80, in get_page_context_from_doctype
    page_info = get_page_info_from_doctypes(path)
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/website/router.py", line 109, in get_page_info_from_doctypes
    controller = get_controller(doctype)
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/model/base_document.py", line 74, in get_controller
    site_controllers[doctype] = _get_controller()
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/model/base_document.py", line 56, in _get_controller
    module = load_doctype_module(doctype, module_name)
  File "/home/fossunited/frappe-bench/apps/frappe/frappe/modules/utils.py", line 207, in load_doctype_module
    raise ImportError('Module import failed for {0} ({1})'.format(doctype, module_name + ' Error: ' + str(e)))
ImportError: Module import failed for Community Course Member (community.community.doctype.community_course_member.community_course_member Error: No module named 'community.community.doctype.community_course_member.community_course_member')
```

**Comment by pateljannat** [comment]
@anandology login to mon.school as an Administrator and delete the doctype Community Course Member. The issue would go away then.

**Comment by anandology** [comment]
Thanks @pateljannat. It worked!
