### ISSUE TITLE
Error to see the course created by the Administrator

### ISSUE THREAD

**Issue by anandology** [fossunited/community#29]
## Describe the Bug

If there a course created by the Administrator, visiting the course page shows the following error.

## Exception

```
Traceback (most recent call last):
  File "/Users/anand/fossunited/frappe-bench/apps/frappe/frappe/website/render.py", line 49, in render
    data = render_page_by_language(path)
  File "/Users/anand/fossunited/frappe-bench/apps/frappe/frappe/website/render.py", line 178, in render_page_by_language
    return render_page(path)
  File "/Users/anand/fossunited/frappe-bench/apps/frappe/frappe/website/render.py", line 194, in render_page
    return build(path)
  File "/Users/anand/fossunited/frappe-bench/apps/frappe/frappe/website/render.py", line 201, in build
    return build_page(path)
  File "/Users/anand/fossunited/frappe-bench/apps/frappe/frappe/website/render.py", line 216, in build_page
    context = get_context(path)
  File "/Users/anand/fossunited/frappe-bench/apps/frappe/frappe/website/context.py", line 28, in get_context
    context = build_context(context)
  File "/Users/anand/fossunited/frappe-bench/apps/frappe/frappe/website/context.py", line 108, in build_context
    update_controller_context(context, context.controller)
  File "/Users/anand/fossunited/frappe-bench/apps/frappe/frappe/website/context.py", line 56, in update_controller_context
    ret = module.get_context(context)
  File "/Users/anand/fossunited/frappe-bench/apps/community/community/www/courses/course.py", line 17, in get_context
    context.instructor = get_instructor(context.course.owner)
  File "/Users/anand/fossunited/frappe-bench/apps/community/community/www/courses/course.py", line 68, in get_instructor
    instructor = frappe.get_doc("Community Member", {"email": owner})
  File "/Users/anand/fossunited/frappe-bench/apps/frappe/frappe/__init__.py", line 841, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/Users/anand/fossunited/frappe-bench/apps/frappe/frappe/model/document.py", line 74, in get_doc
    return controller(*args, **kwargs)
  File "/Users/anand/fossunited/frappe-bench/apps/frappe/frappe/website/website_generator.py", line 17, in __init__
    super(WebsiteGenerator, self).__init__(*args, **kwargs)
  File "/Users/anand/fossunited/frappe-bench/apps/frappe/frappe/model/document.py", line 105, in __init__
    frappe.DoesNotExistError)
  File "/Users/anand/fossunited/frappe-bench/apps/frappe/frappe/__init__.py", line 423, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/Users/anand/fossunited/frappe-bench/apps/frappe/frappe/__init__.py", line 402, in msgprint
    _raise_exception()
  File "/Users/anand/fossunited/frappe-bench/apps/frappe/frappe/__init__.py", line 356, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.DoesNotExistError: Community Member {'email': 'Administrator'} not found
```

## How to Reproduce

1. Login as Administrator
2. Create a course from the desk
3. Visit the course page

## Expected behavior

The course page should be rendered.

**Comment by anandology** [comment]
Either course page should show Administrator as the insructor or not show any instructor at all for this course. But failing is not an option.

**Comment by pateljannat** [comment]
Fixed. Administrator will be shown as the instructor.

![Screenshot 2021-04-21 at 12 59 05 PM](https://user-images.githubusercontent.com/31363128/115514174-774e8100-a2a1-11eb-8a68-b79813fd5dff.png)

**Comment by anandology** [comment]
@pateljannat could you please include the issue number in the commit? That will make it easier to review the changes.
