### ISSUE TITLE
Internal Error on adding a batch with invalid values

### ISSUE THREAD

**Issue by anandology** [fossunited/community#31]
**Describe the bug**

The add a new batch form, when provided with invalid dates for Start Time and End Time, doesn't create the batch and doesn't show any error either. 

The console shows an exception.

**To Reproduce**

1. Add yourself as a mentor for a course from the desk
2. Visit the course page
3. Click on "Add a new batch"
4. Enter "foo" as start time and save
4. See error in the console

**Expected behavior**

An appropriate error should be shown to the user.

**Traceback**

```
Traceback (most recent call last):
  File "/Users/anand/fossunited/frappe-bench/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.handler.handle()
  File "/Users/anand/fossunited/frappe-bench/apps/frappe/frappe/handler.py", line 32, in handle
    data = execute_cmd(cmd)
  File "/Users/anand/fossunited/frappe-bench/apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/Users/anand/fossunited/frappe-bench/apps/frappe/frappe/__init__.py", line 1165, in call
    return fn(*args, **newargs)
  File "/Users/anand/fossunited/frappe-bench/apps/frappe/frappe/website/doctype/web_form/web_form.py", line 430, in accept
    doc.insert(ignore_permissions = True, ignore_mandatory = ignore_mandatory)
  File "/Users/anand/fossunited/frappe-bench/apps/frappe/frappe/model/document.py", line 249, in insert
    self.db_insert()
  File "/Users/anand/fossunited/frappe-bench/apps/frappe/frappe/model/base_document.py", line 362, in db_insert
    ), list(d.values()))
  File "/Users/anand/fossunited/frappe-bench/apps/frappe/frappe/database/database.py", line 146, in sql
    self._cursor.execute(query, values)
  File "/Users/anand/fossunited/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/Users/anand/fossunited/frappe-bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/Users/anand/fossunited/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/anand/fossunited/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/Users/anand/fossunited/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/Users/anand/fossunited/frappe-bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/Users/anand/fossunited/frappe-bench/env/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/Users/anand/fossunited/frappe-bench/env/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1292, "Incorrect time value: 'doo' for column `_9513686da06c00d7`.`tablms batch`.`start_time` at row 1")
```

**Comment by pateljannat** [comment]
Fixed. 

![Screenshot 2021-04-22 at 2 49 56 PM](https://user-images.githubusercontent.com/31363128/115690390-a4bb2d80-a37a-11eb-929a-4561aa1edd28.png)
